import { useEffect,useRef,useState } from "react";
import { motion,useReducedMotion } from "framer-motion";
import { useGame } from "../state/GameContext";
import { useSound } from "../hooks/useSound";
import { finalInvite } from "../data/finalExperience";
import "./FinalCase.css";
const blocks=["Hey Aaru.","I miss the long versions.","The unnecessary details.\nThe conversations that go nowhere.\nThe “wait, there’s more.”","I think we’ve accumulated a ridiculous amount of later.","So I’m claiming my very delayed birthday present.","TIME WITH YOU.","That’s it."];
const prompts=["","Nice try.","Nope.","You're very persistent.","Aaru please.","HAHAHAHA no.","Okay okay.\nLast one."];
const poses=[[0,0,1,0],[.43,-.24,1,-8],[-.42,.22,.65,7],[.3,.28,1.4,-5],[-.38,-.25,1,9],[.42,.12,1,-9],[-.1,.28,1,3]];
export default function FinalRoom(){
 const {visitedFinalRoomIndex,setFinalRoomIndex,goTo}=useGame();const play=useSound();const reduced=useReducedMotion();
 const [index,setIndex]=useState(Math.min(visitedFinalRoomIndex,blocks.length));
 const [stage,setStage]=useState<"message"|"stamp"|"envelope"|"opening"|"letter"|"invite"|"filed">(visitedFinalRoomIndex>=blocks.length+3?"filed":visitedFinalRoomIndex>=blocks.length+2?"invite":visitedFinalRoomIndex>=blocks.length?"stamp":visitedFinalRoomIndex===4?"envelope":visitedFinalRoomIndex>=5?"letter":"message");
 const [attempt,setAttempt]=useState(0);const cooldown=useRef(0);const envelope=useRef<HTMLButtonElement>(null);const field=useRef<HTMLDivElement>(null);const [bounds,setBounds]=useState({width:700,height:440});
 useEffect(()=>{const element=field.current;if(!element)return;const observer=new ResizeObserver(([e])=>setBounds({width:e.contentRect.width,height:e.contentRect.height}));observer.observe(element);return()=>observer.disconnect()},[stage]);
 useEffect(()=>{if(stage!=="stamp")return;play("drawer");const timer=setTimeout(()=>{setStage("invite");setFinalRoomIndex(blocks.length+2)},1600);return()=>clearTimeout(timer)},[stage,play,setFinalRoomIndex]);
 useEffect(()=>{if(stage!=="opening")return;play("drawer");const timer=setTimeout(()=>{setIndex(5);setStage("letter");setFinalRoomIndex(5)},1500);return()=>clearTimeout(timer)},[stage,play,setFinalRoomIndex]);
 function advance(){if(index===3){setIndex(4);setStage("envelope");setFinalRoomIndex(4);return}if(index<blocks.length-1){setIndex(i=>i+1);setFinalRoomIndex(index+1)}else{setIndex(blocks.length);setStage("stamp")}}
 function dodge(){if(stage!=="envelope"||attempt>=6||performance.now()<cooldown.current)return;cooldown.current=performance.now()+700;setAttempt(a=>Math.min(6,a+1))}
 function tapEnvelope(){if(performance.now()<cooldown.current)return;if(attempt<6)dodge();else{setStage("opening")}}
 const pose=poses[attempt];
 return <motion.main className="final-case" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:1.2}}><header className="final-case-header"><span>CASE #2711</span><span>THE MISSING CONVERSATIONS</span></header>
 {stage==="message"&&<button className="case-message" onClick={advance}><motion.p key={index} initial={{opacity:0,y:6}} animate={{opacity:1,y:0}} transition={{duration:.7}}>{blocks[index]}</motion.p><small>tap to continue</small></button>}
 {stage==="stamp"&&<><motion.div className="closed-stamp" initial={reduced?false:{scale:1.5,rotate:-15,opacity:0}} animate={{scale:1,rotate:-7,opacity:1}} transition={{duration:.3}}>CASE CLOSED</motion.div><p className="case-closed-label">CASE #2711<br/>CLOSED</p></>}
 {(stage==="envelope"||stage==="opening"||stage==="letter")&&<motion.p className="envelope-birthday-line" initial={{opacity:0}} animate={{opacity:1}}>{blocks[4]}</motion.p>}
 {(stage==="envelope"||stage==="opening"||stage==="letter")&&<div className={`envelope-field ${stage==="letter"?"envelope-with-letter":""}`} ref={field} onPointerMove={e=>{if(e.pointerType!=="mouse"||attempt>=6)return;const r=envelope.current?.getBoundingClientRect();if(!r)return;const dx=Math.max(r.left-e.clientX,0,e.clientX-r.right),dy=Math.max(r.top-e.clientY,0,e.clientY-r.bottom);if(Math.hypot(dx,dy)<90)dodge()}}><p className="envelope-prompt" aria-live="polite">{stage==="letter"?"":stage==="opening"?"Fine.\nCome get it.":prompts[attempt]}</p><motion.button ref={envelope} className={`chasing-envelope ${stage==="opening"||stage==="letter"?"envelope-opening":""}`} aria-label="Open 2308 envelope" onClick={tapEnvelope} initial={{opacity:0,y:40}} animate={{opacity:1,x:stage!=="envelope"?0:pose[0]*Math.max(0,bounds.width-320),y:stage!=="envelope"?0:pose[1]*Math.max(0,bounds.height-180),scale:stage!=="envelope"?1:pose[2],rotate:stage!=="envelope"?0:pose[3],rotateY:attempt===5&&!reduced?360:0}} transition={reduced?{duration:0}:{type:"spring",stiffness:160,damping:21}}><span className="envelope-flap"/><span className="envelope-number">2308</span><span className="envelope-wax-seal" aria-hidden="true"><span>2711</span></span></motion.button>{stage==="envelope"&&attempt>=6&&<button className="envelope-open-control" onClick={()=>setStage("opening")}>OPEN ENVELOPE</button>}{stage==="letter"&&<motion.article className="envelope-letter" initial={{y:50,opacity:0}} animate={{y:0,opacity:1}} transition={{duration:reduced?0:.8}}><span>A NOTE FOR AARU</span><h1>{blocks[5]}</h1><p>{blocks[6]}</p><button onClick={()=>{setIndex(blocks.length);setStage("stamp");setFinalRoomIndex(blocks.length)}}>CONTINUE →</button></motion.article>}</div>}
 {stage==="invite"&&<motion.article className="summons" initial={reduced?false:{y:80,opacity:0}} animate={{y:0,opacity:1}} transition={{duration:.8}}><span className="summons-kicker">OFFICIAL SUMMONS</span><p className="summons-names">Aaru × Bhuvi</p><h1>THE LONG VERSION</h1><p>No agenda.<br/>No rushing.<br/>No “will tell you later.”</p>{finalInvite.date&&<p>{finalInvite.date}<br/>{finalInvite.startTime} – {finalInvite.endTime}<br/>{finalInvite.location}</p>}<div className="summons-actions"><a href={finalInvite.calendarUrl} target="_blank" rel="noopener noreferrer" onClick={()=>{setStage("filed");setFinalRoomIndex(blocks.length+3)}}>OPEN GOOGLE CALENDAR ↗</a><button data-analytics-action="finish-case" className="case-finish-action" onClick={()=>goTo("complete")}>FINISH THE CASE →</button></div></motion.article>}
 {stage==="filed"&&<div className="case-filed"><span>CALENDAR OPENED ✓</span><p>Case actually closed this time.</p><div className="closed-stamp final-small-stamp">CASE CLOSED</div><button data-analytics-action="finish-case" className="case-finish-action" onClick={()=>goTo("complete")}>CONTINUE →</button></div>}
 </motion.main>
}
