import type {Journey, JourneyEvent} from './model';
import {stations} from './config';
// Fictional, fixed snapshots. Never sourced from visitor storage or the database.
export function makeSampleJourney() {
 const now=Date.now();const at=(seconds:number)=>new Date(now-seconds*1000).toISOString();
 const journey:Journey={session_id:'sample-library-visit',started_at:at(420),last_seen_at:at(0),ended_at:null,snapshot:{current_station:'piece2',previous_station:'piece1',active_ms:330000,idle_ms:90000,state:'active',device:'desktop',viewport:{width:1440,height:900},completed:false,last_interaction:at(8),stations:{intro:{entered_at:at(420),exited_at:at(380),active_ms:40000,idle_ms:0,visits:1,completed:true,scroll:100},piece1:{entered_at:at(380),exited_at:at(300),active_ms:80000,idle_ms:0,visits:1,completed:true,scroll:100},piece2:{entered_at:at(300),active_ms:210000,idle_ms:90000,visits:1,completed:false,scroll:83}},items:{'house-arrest':{station:'piece2',first_open:at(220),last_open:at(90),count:2,dwell_ms:75000},'the-nolan-update':{station:'piece2',first_open:at(180),last_open:at(180),count:1,dwell_ms:45000}},puzzles:{examination:{station:'piece1',started_at:at(370),completed_at:at(305),attempts:2,stage:1,active_ms:65000,idle_ms:0,outcome:'correct'}}}};
 const previous:Journey=structuredClone(journey);previous.session_id='sample-previous-visit';previous.started_at=at(87000);previous.last_seen_at=at(86400);previous.ended_at=at(86400);previous.snapshot.current_station='piece3';previous.snapshot.previous_station='piece2';previous.snapshot.state='disconnected';previous.snapshot.stations.piece2.completed=true;previous.snapshot.stations.piece2.exited_at=at(86520);previous.snapshot.stations.piece3={entered_at:at(86520),active_ms:100000,idle_ms:20000,visits:1,completed:false,scroll:60};previous.snapshot.active_ms+=100000;previous.snapshot.idle_ms+=20000;previous.snapshot.puzzles.connections={station:'piece3',started_at:at(86500),attempts:3,stage:2,active_ms:80000,idle_ms:20000,outcome:'matched'};
 const events:JourneyEvent[]=[{event_id:'sample-open',session_id:journey.session_id,event_type:'book_open',station:'piece2',metadata:{book:'house-arrest'},created_at:at(90)},{event_id:'sample-close',session_id:journey.session_id,event_type:'book_close',station:'piece2',metadata:{book:'the-nolan-update'},created_at:at(135)},{event_id:'sample-enter',session_id:journey.session_id,event_type:'station_enter',station:'piece2',metadata:{},created_at:at(300)},{event_id:'sample-attempt',session_id:previous.session_id,event_type:'puzzle_attempt',station:'piece3',metadata:{puzzle:'connections',outcome:'matched',stage:2},created_at:at(86410)}];
 return {journeys:[journey,previous],events,now,stationCount:stations.length};
}
